### ISSUE TITLE
Downloading (Saving) and Uploading Blocks has stopped working

### ISSUE THREAD

**Issue by ptal78** [rafaelaroca/BIPES_ui_testing#14]
Saving (downloading) blocks now just presents with a white screen, but two days ago it was working fine to generate xml code.

Uploading couldn't load the file I had created and downloaded the other day.

**Comment by JorgeGMarques** [comment]
Hello!

I already merged the fix into master, but our server has not yet been updated.
I'll leave the issue opened until the server has been updated.

**Comment by rafaelaroca** [comment]
Thanks for the fix Jorge! Server updated. @ptal78, just tested. Hope it works well for you now!
