### ISSUE TITLE
Chart labels are "leaking" to others tabs.

### ISSUE THREAD

**Issue by JorgeGMarques** [rafaelaroca/BIPES_ui_testing#21]
Pretty sure changing `#content_*` rule from`visibility: hidden;` to `display:none;` will fix. 
Also, to make  `#content_*` scrollable,  just add `overflow-y: auto` to `ui/style.css` (line 192).

(`*` is the desired tab's id)

![Screenshot from 2021-07-05 13-48-24](https://user-images.githubusercontent.com/2892061/124501422-e6634e00-dd97-11eb-94a8-fdd3b1504012.png)

**Comment by rafaelaroca** [comment]
Hi Jorge! Thanks for the report! I think the bug does not exist now, as I removed all the code related to this graph, to include an ifram to freeboard dashboard, starting a process of possible integration of freeboard on BIPES UI. Here are some details of the first test:
[https://rafaelaroca.wordpress.com/2021/07/08/bipes-iot-dashboard/](https://rafaelaroca.wordpress.com/2021/07/08/bipes-iot-dashboard/)
