### ISSUE TITLE
Ultrasonic Block has an odd connection problem

### ISSUE THREAD

**Issue by ptal78** [rafaelaroca/BIPES_ui_testing#25]
Esp32   Ultrasonic block has an error with any other block connected after it:
 
For example, the following code example works unless the OLED block is connected after the Ultrasonic block.
 
Also, can I2C Init have a   default value at variable I2C?
Eg. 1
Or -1

![image](https://user-images.githubusercontent.com/24988399/125254754-1bdedd00-e33e-11eb-91f4-522e677e5b73.png)

**Comment by rafaelaroca** [comment]
Fixed. Could you test, please? Thanks again!

**Comment by ptal78** [comment]
Excellent - Thanks
