### ISSUE TITLE
Python code fails to generate when NeoPixel color is set with a variable - please fix ASAP

### ISSUE THREAD

**Issue by ptal78** [rafaelaroca/BIPES_ui_testing#30]
I think the variables used to work with the NeoPixel, but now it doesn't.

![image](https://user-images.githubusercontent.com/24988399/126040980-bfe73d57-ec25-4fe0-88ce-0ce4848af427.png)

From the image, everything works normally until the variable is placed in the 'color' block.
The python code fails to generate.

As you can see, the variable I set is a number, and as the number 123 is within the 0-255 required value, it should be acceptable within the color block. But it fails to generate any python code as soon as this variable is applied in either of the three variable locations.

Can you please fix this ASAP?

**Comment by JorgeGMarques** [comment]
Hello,

The issue has been resolved, but keep in mind that `neopixel*` blocks are only available in the `beta2serial` version for now.
Quick test: https://bipes.net.br/beta2serial/ui/#tzqzae

The issue was due to the misuse of the `Blockly.JavaScript` functions. Since we use the Python generator,we should always invoke  `Blockly.Python` instead (both are not interchangeable, even though not always cause bugs).

Best regards,

**Comment by ptal78** [comment]
Hi,

I'm not sure what's happening. You had this almost perfect 4 hours ago with the new neopixel write block and everything. Even the variables started producing code. 

All I said was you had double brackets, but now it's all screwed up and you've taken away the write neopixel block. Maybe you are just still working on it - are you? Because the main line of code to load the data is missing.

Where is this line?

np[0] = (255, 255, 255)

**Comment by JorgeGMarques** [comment]
Hi,

please force refresh your browser cache, just committed cbf94e1 to remove the extra parenthesis and change the `ADC` block to `read()`, quick test: http://www.bipes.net.br/beta2/ui/#re4ih9

**Comment by JorgeGMarques** [comment]
`XML` files are ridiculously persistent in modern browser, if "`CTRL + F5`" won't solve, please "`CTRL + F5`" these files:

`http://www.bipes.net.br/beta2/ui/toolbox_esp32.xml`
`http://www.bipes.net.br/beta2serial/ui/toolbox_esp32.xml`

**Comment by ptal78** [comment]
Wonderful. I cleared my cache and it seems to works perfectly now.

Thankyou so much
