### ISSUE TITLE
Pins Not Defined for ESP32 - only works with ESP8266

### ISSUE THREAD

**Issue by ptal78** [rafaelaroca/BIPES_ui_testing#8]
Bipes will not define the pins for ESP32 device at http://bipes.net.br/beta2/ui/. It seems to only load pins for the ESP8266

**Comment by ptal78** [comment]
This was tested over both WebREPL and over USB to Serial. At no point were the ESP32 pins defined.

**Comment by rafaelaroca** [comment]
Hi!!

Just fixed the issue. Please, keep in mind that these pinouts are only a convenience. If you want, you can just use the "Number" block to define a pin. Anyway, pin definitions for ESP32 added in both versions. If you could try it again, we thank you!

best regards
Rafael

**Comment by ptal78** [comment]
Can these pins be re-ordered and cataloged by their digital pin number to make it easy to find them?
